### ISSUE TITLE
GPL vs MIT license

### ISSUE THREAD

**Issue by munyari** [rustyhorde/readline-sys#13]
I'm not very knowledgeable about licensing, but GNU readline is licensed under GPL. Does that not mean that this this library is required to also be licensed with GPL, not MIT? For reference https://en.wikipedia.org/wiki/GNU_Readline#Choice_of_the_GPL_as_GNU_Readline.27s_license

**Comment by CraZySacX** [comment]
Yes it does, good catch.

**Comment by munyari** [comment]
I'll be happy to make changes tomorrow morning

**Comment by CraZySacX** [comment]
Already done, thanks though.
