### ISSUE TITLE
rl_catch_signals and signal handling

### ISSUE THREAD

**Issue by dagit** [rustyhorde/readline-sys#3]
While testing this crate and the CtrlC crate on FreeBSD I noticed a difference in the way readline works on FreeBSD (compared to linux). I have to set `rl_catch_signals = 0` before calling `readline` if I want to do my own signal handling. Otherwise my program is exiting when I hit ctrl-c.

Locally I have a modification where I added `rl_catch_signals` to the private `ext_readline` module and I set that to 0 in the unsafe block that calls `ext_readline::readline`. This works for me, but probably not all users will want it hard coded to 0?

I'm not sure what is the right way to expose this safely. Do you have any thoughts on how to handle this?

**Comment by CraZySacX** [comment]
Create a copy of the function.

Add ```#[cfg(target_os = "freebsd")]``` as an attribute on the version where you set the value to 0.

On the original add ```#[cfg(not(target_os = "freebsd"))]``` as an attribute.

**Comment by dagit** [comment]
That would work and make the behavior similar to linux for me, but I'm not sure if it's the right way. It's probably better to expose `rl_catch_signals`, but I don't know rust well enough to know the right way to do that. For now I've decided to stop using freebsd so I no longer need the fix. I say we just close this and revisit if someone else has this problem.

Thanks!
