### ISSUE TITLE
Add Support for More History Features

### ISSUE THREAD

**Issue by rgardner** [rustyhorde/readline-sys#5]
A [crates.io search for readline](https://crates.io/search?q=readline) shows that this crate has the most stars. After looking at the other implementations, this also seems to be the most complete. To make this library more useful for my own project, this library should add support for more history functions. For my project, I'd like:

- [ ] history_list
- [x] history_clear
- [x] history_stifle
- [ ] history_expand
- [ ] history_search

I'm happy to work on these bindings, I just wanted to check first that these additions were welcome.

**Comment by CraZySacX** [comment]
Yeah feel free to work on extra functionality.

**Comment by munyari** [comment]
@rgardner have you made any progress on these features?

**Comment by CraZySacX** [comment]
The entire history API has been implemented now, including list, expand, and search.   https://rustyhorde.github.io/readline-sys/readline-sys/rl_sys/history/index.html

Marking this one closed.
